import React from 'react';
import Link from 'next/link';
import { AlertTriangle, Scale, Code, Banknote, ShieldAlert, Mail } from 'lucide-react';

export const metadata = {
    title: 'Disclaimer - AlphaPrime',
    description: 'Legal disclaimer and limitation of liability for using AlphaPrime tools including Word Counter, PrimeLink, and more.',
};

const Section = ({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) => (
    <div className="mb-12">
        <div className="flex items-center gap-3 mb-4">
            <span className="text-black w-8 h-8 flex-shrink-0">{icon}</span>
            <h2 className="text-2xl font-bold text-black m-0">{title}</h2>
        </div>
        <div className="text-gray-800 space-y-3">{children}</div>
    </div>
);

export default function Disclaimer() {
    return (
        <div className="container mx-auto px-4 py-12 relative z-10">
            <div className="text-center max-w-3xl mx-auto mb-16">
                <div className="inline-flex items-center justify-center w-20 h-20 rounded-2xl bg-zinc-100 border border-zinc-200 mb-8 shadow-sm">
                    <ShieldAlert className="w-10 h-10 text-black" />
                </div>
                <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold mb-6 tracking-tight text-black">
                    Legal Disclaimer
                </h1>
                <p className="text-lg text-gray-800 leading-relaxed max-w-2xl mx-auto">
                    Important limitations of liability and usage warnings regarding AlphaPrime utilities and services.
                </p>
                <div className="mt-8 text-sm text-gray-800 font-medium">
                    Effective Date: <span className="text-black font-bold">February 25, 2026</span>
                </div>
            </div>

            <div className="max-w-4xl mx-auto bg-white p-8 md:p-12 rounded-3xl border border-zinc-200 shadow-sm">
                <div className="prose prose-zinc max-w-none">

                    <Section icon={<AlertTriangle className="w-8 h-8" />} title="1. General Informational Purpose">
                        <p>
                            All tools, algorithms, and content provided on AlphaPrime (including but not limited to Word Counter, Base64 Converter, Diff Checker, and Case Converter) are provided for general informational and productivity purposes only. They are not intended to replace professional, legal, or technical advice.
                        </p>
                    </Section>

                    <Section icon={<Scale className="w-8 h-8" />} title="2. No Guarantee of Accuracy">
                        <p>
                            While we strive to ensure the algorithms powering our tools are robust, <strong className="text-black">AlphaPrime makes no warranties concerning the accuracy, likely results, or reliability</strong> of the use of these tools. You use the provided outputs at your own absolute risk. We are not liable for errors in parsed text, character counts, or color hex calculations.
                        </p>
                    </Section>

                    <Section icon={<Code className="w-8 h-8" />} title="3. Software & Security Tools (Password Generator & PrimeLink)">
                        <p>
                            <strong className="text-black">Password Generator:</strong> We are not liable for any compromises, data breaches, or unauthorized access to systems secured with passwords generated by our tool. Generating a password does not guarantee invulnerability against cyber attacks.
                        </p>
                        <p className="mt-4">
                            <strong className="text-black">PrimeLink Chat:</strong> PrimeLink provides an encrypted, ephemeral chat channel. However, we cannot guarantee absolute security against highly sophisticated state-level interception or endpoint compromise (e.g., malware on your device). Users employ PrimeLink for sensitive communications entirely at their own risk.
                        </p>
                    </Section>

                    <Section icon={<ShieldAlert className="w-8 h-8" />} title="5. Local Storage Loss">
                        <p>
                            Because several of our tools rely on your browser&apos;s Local Storage for enhanced privacy and speed, <strong className="text-black">we cannot recover lost data</strong> if you clear your browser history, use incognito mode, or uninstall the AlphaPrime PWA/Android App. You are solely responsible for manually backing up any critical data (like exported data).
                        </p>
                    </Section>

                    <div className="border-t border-zinc-200 pt-8 mt-12 text-center">
                        <p className="text-gray-800 mb-2">Questions about this disclaimer?</p>
                        <Link href="/contact" className="inline-flex items-center gap-2 text-black hover:text-gray-800 font-bold transition-colors">
                            <Mail className="w-5 h-5" />
                            Contact Legal Team
                        </Link>
                        <p className="text-xs text-gray-700 mt-6">
                            AlphaPrime · <Link href="/privacy" className="underline hover:text-black">Privacy Policy</Link> · <Link href="/terms" className="underline hover:text-black">Terms</Link>
                        </p>
                    </div>

                </div>
            </div>
        </div>
    );
}
